# This is a generated file. Not intended for manual editing.
services:
  api:
    build:
      context: "D:\\Development\\personal\\repos\\Famyok\\api\\src\\Famyok"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Famyok.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "famyok.api:dev"
    ports: []
    volumes:
    - "D:\\Development\\personal\\repos\\Famyok\\api\\src\\Famyok:/app:rw"
    - "D:\\Development\\personal\\repos\\Famyok\\api\\src:/src:rw"
    - "C:\\Users\\radek.pelikan\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
  identity:
    build:
      context: "D:\\Development\\personal\\repos\\Famyok\\api\\src\\Famyok.IdentityProvider"
      dockerfile: "Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net9.0/Famyok.IdentityProvider.dll"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "famyok.identity:dev"
    ports: []
    volumes:
    - "D:\\Development\\personal\\repos\\Famyok\\api\\src\\Famyok.IdentityProvider:/app:rw"
    - "D:\\Development\\personal\\repos\\Famyok\\api\\src:/src:rw"
    - "C:\\Users\\radek.pelikan\\.nuget\\packages:/home/app/.nuget/packages"
    working_dir: "/app"
